# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('P', 'Pluvial'), ('WS', 'Velocidad Viento'), ('WD', 'Dirsensor_ideccion Viento'), ('UV', 'UV'), ('TEMP', 'Temperatura'), ('HUM', 'Humedad'), ('CO', 'CO'), ('CO2', 'CO2')], default='Pluvial', max_length=255)),
                ('is_active', models.BooleanField(default=False, editable=False)),
                ('date_registered', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default='error')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location_longitude', models.FloatField(editable=False, null=True)),
                ('location_latitude', models.FloatField(editable=False, null=True)),
                ('location_altitude', models.FloatField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=False, editable=False)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Station'),
        ),
    ]
