# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='data',
            field=models.TextField(default='error'),
        ),
        migrations.AlterField(
            model_name='station',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
