# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('home', '0002_auto_20170929_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City'),
        ),
    ]
