# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_sensor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_activity_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='last_activity_date',
            field=models.DateTimeField(null=True),
        ),
    ]
