# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171203_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_activity_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('P', 'Pluvial'), ('WS', 'Velocidad Viento'), ('WD', 'Direccion Viento'), ('UV', 'UV'), ('TEMP', 'Temperatura'), ('HUM', 'Humedad'), ('CO', 'CO'), ('CO2', 'CO2')], default='Pluvial', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='last_activity_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True),
        ),
    ]
