# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_station_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
